### PR TITLE
Kontainer can use es6 classes as factories

### PR DESCRIPTION
**Pull request by donatasbacius**
Thought it would be useful. Anyone interested?

### CODE REVIEW

**Comment by cdelaorden** [comment]
It looks good! It would be terrific if you could create a small example (either for documentation or the examples folder). Can you do something like that?

**Comment by donatasbacius** [comment]
Sure. Please review and publish if you're happy with it :)

**Comment by cdelaorden** [comment]
Funny example indeed :) Looks fine to me, the only missing thing is an specific test for this use case. Would it be an abuse to ask you to add one?

**Comment by donatasbacius** [comment]
No probs - added a couple of tests and updated travis-ci yaml to run on node v5.5.0. The tests were a bit hairy tho. What are your thoughts?

**Comment by cdelaorden** [comment]
Thanks mate!

I'll review it during the weekend and merge ASAP. I agree the test looks a bit hacky, but it'll probably do for now.

We'll be studying the idea of moving to node 5.5 so we'll be able to declare "real" classes instead of using eval soon.

Thanks @donatasbacius , yours is the first collaboration we receive on this project. :)

**Comment by donatasbacius** [comment]
@cdelaorden - it's been a pleasure to contribute. Looking forward to use this in my project :)

**Comment by donatasbacius** [comment]
Bump :)

**Comment by cdelaorden** [comment]
:+1: :)

**Pull request merged**
